// This file is auto-generated by Supabase CLI in real projects.
// For new Lovable projects, this stub gives the client a `Database` type
// to import. Once you add tables, regenerate with `supabase gen types`.
export type Json = string | number | boolean | null | { [k: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
